# DB config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##GIBUHAGAE
    password: GIBUHAGAE

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

#file upload
#  servlet:
#    multipart:
#      location: C:/Lecture/10_spring/02_spring-web-mvc/chap06-file-upload
#      max-file-size: 10MB
#      max-request-size: 10MB