# DB config
server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##GIBUHAGAE
    password: GIBUHAGAE

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
