# DB config
server:
  port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##GIBUHAGAE
    password: GIBUHAGAE

  # file upload config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/Lecture/00_Project/subproject/gibuhagae/

# Mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml

# image upload dir
image:
  image-dir: src/main/resources/static/uploadFiles/**/*.jpg