# oauth 등록
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: PmDrXlVeXulX2pwGIV3c
            client-secret: duqRFFPRVk
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response